namespace Domain.Entity.Enum;

/**
 * DEFINE QUAIS SÃO OS TIPOS DE PERMISSÕES QUE UM
 * MANAGER PODE TER.
 */
public enum Permission
{
    CAN_ADD_MEMBERS = 1,
    CAN_EDIT_MEMBERS = 2,
    CAN_DELETE_MEMBER = 3,
    CAN_GET_MEMBERS = 4,
    CAN_ADD_PROFESSIONALS = 5,
    CAN_EDIT_PROFESSIONALS = 6,
    CAN_DELETE_PROFESSIONALS = 7,
    CAN_GET_PROFESSIONALS = 8,
    CAN_SEND_NOTIFICATIONS = 9
}